name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: curl -LO https://raw.githubusercontent.com/clearfraction/tools/master/build.sh
      - run: chmod +x build.sh
      - run: echo "Check the length of GL env key: "
      - run: env | grep -i gitlab | wc -c
      - run: docker run --privileged --cap-add=SYS_ADMIN -e GITLAB_API_KEY=$GITLAB_API_KEY -v $(pwd):/home clearlinux:latest sh -c "cd /home && ./build.sh"
